# Generated by Django 3.2.15 on 2022-09-27 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_auto_20220927_1018"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookinstance",
            options={
                "ordering": ["due_back"],
                "permissions": (("can_mark_returned", "Set book as returned"),),
            },
        ),
    ]
